language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - jq
branches:
  only:
  - master
before_deploy:
  - git config --local user.name "hobbyquaker"
  - git config --local user.email "hobbyquaker@gmail.com"
  - source ./addon_tmp/node-red/versions
  - git tag "v$ADDON_VERSION-$TRAVIS_BUILD_NUMBER"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
after_deploy:
  - gem install octokit
  - ./github_release.rb -s $GITHUB_OAUTH_TOKEN -r hobbyquaker/ccu-addon-node-red -c CHANGELOG.md -t v$ADDON_VERSION-$TRAVIS_BUILD_NUMBER