language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - jq
branches:
  only:
  - master
install: true
script: true
before_deploy:
  - git config --local user.name "hobbyquaker"
  - git config --local user.email "hobbyquaker@gmail.com"
  - ./build.sh
  - source ./addon_tmp/redmatic/versions
  - git tag "v$VERSION_ADDON"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
after_deploy:
  - gem install octokit
  - ./github_release.rb -s $GITHUB_OAUTH_TOKEN -r hobbyquaker/RedMatic -c CHANGELOG.md -t v$VERSION_ADDON