language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - jq
branches:
  only:
  - master
before_deploy:
  - ./build.sh
  - git config --local user.name "hobbyquaker"
  - git config --local user.email "hobbyquaker@gmail.com"
  - git tag "Build-$TRAVIS_BUILD_NUMBER"
  - source ./addon_tmp/node-red/versions
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  body: * Node.js $NODE_VERSION\n* npm $NPM_VERSION\n* Node-RED $RED_VERSION\n* Node-RED Dashboard $DASHBOARD_VERSION\n* node-red-contrib-ccu $RED_CCU_VERSION
